describe("switch account" , function()
{
    beforeEach('resolution', function()
    {
        cy.viewport(1920,1080)
    })
    it("login", function()
    {
        cy.visit("https://members-qa.coyni.com/login")
        cy.get("#Email").type("auto@yopmail.com")
        cy.get("#Password").type("Admin@123")
        cy.get('[type=submit]').click()
        cy.get('.relative > :nth-child(1)').type('123456')
        cy.wait(5000)
        
    })
    // it("user creating new company", function()
    // {
    //     cy.get('.DashboardMenu_mainDiv__kfX1C').click()
    //    // cy.get('.UserNameDropDown_header__y-U81').click()
    //     //cy.get('.UserNameDropDown_dba__WtKbr').click()
    //       cy.contains('Add New DBA').click()
    //       cy.get('.AddNewBusinessModal_hover_card__XCtyN').eq(0).click()
    //       cy.wait(2000)
    //       cy.get('.w-60.h-9.rounded-full.font-semibold').click()
    // })
    it.skip("Company Information", function()
    {
    cy.contains('Start Application').click()
    cy.wait(2000)
    cy.get('#company-name').type('GMT PVT LMT')
    cy.wait(2000)
    cy.get('[height="8"]').eq(0).click()
    cy.get('[tabindex="0"]').eq(0).contains('Sole Proprietorship / Single LLC').click()
    cy.wait(2000)
    cy.get('[name="entityValue"]').type('66-6666666')
    cy.wait(2000)
    cy.get('#email').type('hello@gmail.com')
    cy.get('#phone-number').type('8282654525',{force:true})
    cy.get('#address-line-1').type('hyderabad',{force:true})
    cy.get('#address-line-2').type('hyderabad',{force:true})
    cy.get('#city').type('telangana')
    cy.wait(2000)
    cy.get('[height="8"]').eq(1).click()
    cy.get('[tabindex="0"]').eq(1).contains('Alabama').click()
    cy.wait(2000)
    cy.get('#zip-code').type('13423',{force:true})
    cy.get('[type=file]').eq(0)
    cy.get('[type=file]').attachFile('799.jpg')
    //cy.wait(2000)
    //cy.get('[type=file]').eq(1)
    //cy.get('[type=file]').attachFile('obito.jpg')
    //cy.wait(2000)
    //cy.get('[type=file]').eq(2)
    //cy.get('[type=file]').attachFile('220764.jpg')
    cy.contains('Next').click()
    })
    it.skip("DBA Information", function()
    {
        //cy.get('.grow > .flex-row > :nth-child(2)').click()
        cy.contains('Continue Application').click()
        cy.wait(2000)
//cy.contains('No').click()
cy.wait(2000)
cy.get('#dba-name').clear().type('Marketing',{force:true})
cy.wait(2000)
cy.get('[height="8"]').eq(0).click()
cy.get('[tabindex="0"]').eq(0).contains('Massage Parlors (7297)').click()
cy.wait(2000)
cy.get('[name="email"]').eq(0).type('hello@gmail.com',{force:true})
cy.get('#phone-number').type('1325436787',{force:true})
cy.wait(3000)
cy.get('[name="monthlyProcessingVolume"]').type('1',{force:true}).clear().type('3000')
cy.get('#high-ticket').type('1',{force:true}).clear().type('2000')
cy.get('#average-ticket').type('1',{force:true}).clear().type('1000')
cy.get('#address-line-1').clear().type('hyderabad',{force:true})
cy.get('#city').clear().type('telangana',{force:true})
cy.wait(2000)
    cy.get('[height="8"]').eq(1).click()
    cy.get('[tabindex="0"]').eq(1).contains('Alabama').click()
    cy.get('#zip-code').type('12354',{force:true})
    cy.wait(2000)
    //cy.get('[height="8"]').eq(2).click()
    //cy.get('[tabindex="0"]').eq(2).contains('Pacific (PST)').click()
    //cy.wait(2000)
    cy.get('.w-44.h-9.rounded-full.font-semibold').click()
    })
    it.skip("Beneficial Owner", function()
    {
        cy.get('.w-60').click()
cy.get('#first-name-0').type('kalyan')
cy.get('#last-name-0').type('kk')
cy.get('#date-of-birth-0').type('01121999',{force:true})
cy.get('#ssn-0').type('765-43-4567',{force:true})
cy.get('#ownership-0').type('56',{force:true})
cy.wait(3000)
cy.get('#address-line-1-0').type('hyd',{force:true})
cy.wait(3000)
cy.get('#city-0').type('hyd',{force:true})
cy.get('[height="8"]').click()
    cy.get('[tabindex="0"]').contains('Alabama').click()
    cy.get('#zip-code-0').clear().type('64532')
    cy.get('[type="radio"]').eq(0).click()
    cy.get('[type=file]').attachFile('799.jpg')
   // cy.get('.w-44.h-9.rounded-full').eq(0).click()
    cy.wait(4000)
    cy.get('.w-44.h-9.rounded-full').eq(1).click()
   })
//    it.skip("bank Account", function()
//    {
//     cy.get('.w-60').click()
//     cy.wait(2000)
// cy.get('#routingNumber').type('122105278',{force:true})
// cy.get('[name="confirmRouting"]').type('122105278',{force:true})
// cy.get('#accountNumber').type('0000000017', {force:true})
// cy.get('#confirmAccountNumber').type('0000000017', {force:true})
// cy.get('.w-44.h-9.rounded-full.font-semibold').click()
//    })
   it("agreement", function()
   {
    cy.contains('Continue Application').click()
    // cy.get(':nth-child(1) > .Agreements_agreementBox__wVw2H > :nth-child(2) > .mr-6').click()
    // cy.wait(10000)
    // cy.get(':nth-child(2) > .Agreements_agreementBox__wVw2H > :nth-child(2) > .mr-6').click()
    // cy.wait(10000)
    // cy.get('.Agreements_apiData__pSdGe.relative').scrollTo("bottom", { duration: 16000 })
    //     cy.get('[type="checkbox"]').click()
    //     cy.wait(2000)
    //     cy.get('.w-44.h-9.rounded-full.font-semibold').click()
    //     cy.get(':nth-child(2) > .Agreements_agreementBox__wVw2H > :nth-child(2) > .mr-6').click()
    //     cy.wait(10000)
    // cy.get(':nth-child(3) > .Agreements_agreementBox__wVw2H > :nth-child(2) > .px-0\.5').click()
    // cy.wait(5000)
    // cy.get('.Agreements_apiData__pSdGe.relative').scrollTo("bottom", { duration: 16000 })
    //     cy.get('[type="checkbox"]').click()
    //     cy.wait(2000)
    //     cy.get('.w-44.h-9.rounded-full.font-semibold').click()
    cy.wait(3000)
        cy.get('.w-44.h-9.rounded-full.font-semibold').click()
   })
   it("Application Summary", function()
   {
    cy.get('[type="checkbox"]').click()
    cy.get('.ApplicationSummary_fontStyle__oM7ra').type('kalyan')
})
})